import React, { FormEvent, useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import './styles.css';
import { AuthSession, canManageRisk, clearSession, createSession, loadSession, roleLabel, saveSession } from './auth';
const API = import.meta.env.VITE_API_URL || 'http://localhost:8000';
const money = (value: number) => new Intl.NumberFormat('en-IN', { style: 'currency', currency: 'INR', maximumFractionDigits: 0 }).format(value || 0);

function Login({ done }: { done: (s: AuthSession) => void }) { const [username, setUsername] = useState(''); const [password, setPassword] = useState(''); const [error, setError] = useState(''); async function submit(e: FormEvent) { e.preventDefault(); try { const r = await fetch(`${API}/api/v1/auth/login`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ username, password }) }); if (!r.ok) { setError(r.status === 401 ? 'Invalid username or password.' : 'Sign-in is unavailable.'); return; } const d = await r.json(); const s = createSession(d.access_token, d.role); if (!s) { setError('Invalid or expired session.'); return; } saveSession(s); done(s); } catch { setError('The API is unavailable.'); } } return <main className="login-page"><form className="login-card" onSubmit={submit}><span className="eyebrow">SENTINELLEDGER / SECURE ACCESS</span><h1>Sign in to the risk workspace.</h1><label>Username<input value={username} onChange={e => setUsername(e.target.value)} required /></label><label>Password<input type="password" value={password} onChange={e => setPassword(e.target.value)} required /></label>{error && <p className="auth-message">{error}</p>}<button>Sign in</button></form></main>; }

function Dashboard({ active, onLogout }: { active: AuthSession; onLogout: () => void }) {
 const [view, setView] = useState('executive'); const [data, setData] = useState<any>(null); const [error, setError] = useState(''); const [asset, setAsset] = useState<any>(null); const [loading, setLoading] = useState(false);
 const request = async (path: string) => { const r = await fetch(`${API}${path}`, { headers: { Authorization: `Bearer ${active.token}` } }); if (r.status === 401) { onLogout(); throw new Error('Session expired'); } if (!r.ok) throw new Error('Unable to load dashboard data'); return r.json(); };
 useEffect(() => { setLoading(true); setError(''); setAsset(null); const path = view === 'executive' ? '/api/v1/dashboard/executive' : view === 'technical' ? '/api/v1/dashboard/technical' : '/api/v1/business-units'; request(path).then(setData).catch(e => setError(e.message)).finally(() => setLoading(false)); }, [view, active.token]);
 async function openAsset(id: number) { setLoading(true); try { setAsset(await request(`/api/v1/assets/${id}`)); } catch (e: any) { setError(e.message); } finally { setLoading(false); } }
 function logout() { onLogout(); }
 const nav = [{ id: 'executive', label: 'Executive' }, { id: 'technical', label: 'Technical' }, { id: 'business', label: 'Business units' }];
 return <main><header><div><span className="eyebrow">SENTINELLEDGER / {roleLabel[active.role]} WORKSPACE</span><h1>Cyber risk, expressed in business terms.</h1></div><div className="account"><span>{roleLabel[active.role]}</span><button onClick={logout}>Log out</button></div></header><nav>{nav.map(n => <button key={n.id} className={view === n.id ? 'active' : ''} onClick={() => setView(n.id)}>{n.label}</button>)}</nav>{loading && <p className="state">Loading persisted synthetic data…</p>}{error && <p className="state error">{error}</p>}{!loading && !error && data && view === 'executive' && <Executive data={data} openAsset={openAsset} />}{!loading && !error && data && view === 'technical' && <Technical data={data} />}{!loading && !error && data && view === 'business' && <Business data={data} />}{asset && <AssetDetail asset={asset} close={() => setAsset(null)} />}</main>;
}
function App() { const [session, setSession] = useState<AuthSession | null>(() => loadSession()); if (!session) return <Login done={setSession} />; return <Dashboard active={session} onLogout={() => { clearSession(); setSession(null); }} />; }
function Executive({ data, openAsset }: any) { const r = data.enterprise; const peak = Math.max(...data.risk_trend.map((x: any) => x.financial_loss), 1); return <><p className="fresh">Calculated {r.calculated_at ? new Date(r.calculated_at).toLocaleString() : 'not yet available'} / persisted synthetic estimates</p><section className="metrics"><Metric label="Enterprise risk score" value={`${r.risk_score} / 100`} /><Metric label="Financial exposure" value={money(r.financial_impact)} /><Metric label="Expected annual loss" value={money(r.eal)} /><Metric label="95% Cyber VaR" value={money(r.var_95)} /></section><section className="panel"><h2>Financial risk trend</h2>{data.risk_trend.length ? <div style={{ display: 'flex', alignItems: 'end', height: 160, gap: 18 }}>{data.risk_trend.map((x: any) => <div key={x.period} style={{ height: '100%', display: 'grid', alignItems: 'end' }}><i style={{ display: 'block', width: 34, height: `${(x.financial_loss / peak) * 100}%`, background: '#65dcb4' }} /><small>{x.period}</small></div>)}</div> : <p className="state">No incident trend available.</p>}</section><section className="grid"><article className="panel"><h2>Top risk contributors</h2>{data.top_contributors.length ? data.top_contributors.map((x: any) => <button className="row" key={x.asset_id} onClick={() => openAsset(x.asset_id)}><b>{x.name}</b><span>{money(x.eal)} EAL</span><em>Risk {x.risk_score}</em></button>) : <p className="state">No persisted risk assessments. Seed and recalculate risk data.</p>}</article><article className="panel"><h2>Risk-reduction opportunities</h2>{data.opportunities.map((x: any) => <div className="driver" key={x.code}><b>{x.name}</b><span>{money(x.cost)}</span><em>{money(x.risk_reduction)} estimated reduction</em></div>)}</article></section></>; }
function Technical({ data }: any) { return <><p className="fresh">Telemetry freshness: {data.telemetry_freshness ? new Date(data.telemetry_freshness).toLocaleString() : 'No telemetry received'}</p><section className="metrics">{Object.entries(data.counts).map(([k, v]) => <Metric key={k} label={k} value={String(v)} />)}</section><section className="panel"><h2>Technical posture</h2><p className="state">Counts are drawn from persisted assets, vulnerabilities, incidents, controls, and threat scenarios.</p></section></>; }
function Business({ data }: any) { return <section className="panel"><h2>Business-unit risk</h2>{data.items.length ? data.items.map((x: any) => <div className="driver" key={x.id}><b>{x.name}</b><span>Risk {x.risk.risk_score}</span><em>{money(x.risk.eal)} EAL / {money(x.risk.var_95)} P95 VaR</em></div>) : <p className="state">No business units available.</p>}</section>; }
function AssetDetail({ asset, close }: any) { return <section className="panel detail"><button onClick={close}>Close detail</button><h2>{asset.name}</h2><p>{asset.type} · Criticality {asset.criticality} · {asset.internet_exposed ? 'Internet exposed' : 'Internal'}</p><section className="metrics"><Metric label="Risk score" value={`${asset.risk.risk_score} / 100`} /><Metric label="Financial exposure" value={money(asset.risk.financial_impact)} /><Metric label="EAL" value={money(asset.risk.eal)} /><Metric label="P95 VaR" value={money(asset.risk.var_95)} /></section><h2>Risk drivers</h2><pre>{JSON.stringify(asset.risk.drivers, null, 2)}</pre><h2>Vulnerabilities</h2>{asset.vulnerabilities.length ? asset.vulnerabilities.map((v: any) => <p key={v.cve_id}>{v.cve_id} · CVSS {v.cvss} · {v.status}</p>) : <p className="state">No vulnerabilities recorded.</p>}<h2>Relevant controls</h2>{asset.controls.length ? asset.controls.map((c: any) => <p key={c.name}>{c.name} · {c.category} · {Math.round(c.effectiveness * 100)}% effectiveness</p>) : <p className="state">No linked investment controls.</p>}</section>; }
function Metric({ label, value }: { label: string; value: string }) { return <article><p>{label}</p><strong>{value}</strong></article>; }
createRoot(document.getElementById('root')!).render(<React.StrictMode><App /></React.StrictMode>);
